// Regenerates src/app/components/shared/icons.ts with the offline icon data
// for every Iconify icon name referenced in src/. Run after adding/removing
// icons:  node scripts/generate-icons.mjs
import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { getIcons } from "@iconify/utils";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const srcDir = join(root, "src");
const outFile = join(srcDir, "app", "components", "shared", "icons.ts");

const files = [];
(function walk(dir) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full);
    else if (/\.(tsx?|mdx?)$/.test(entry) && !full.endsWith("icons.ts"))
      files.push(full);
  }
})(srcDir);

const used = new Map(); // prefix -> Set of names
for (const file of files) {
  const text = readFileSync(file, "utf8");
  for (const match of text.matchAll(/["'](lucide|ic):([a-z0-9-]+)["']/g)) {
    const [, prefix, name] = match;
    if (!used.has(prefix)) used.set(prefix, new Set());
    used.get(prefix).add(name);
  }
}

const chunks = [];
const missing = [];
for (const [prefix, names] of [...used.entries()].sort()) {
  const collection = JSON.parse(
    readFileSync(
      join(root, "node_modules", "@iconify-json", prefix, "icons.json"),
      "utf8",
    ),
  );
  const sorted = [...names].sort();
  const subset = getIcons(collection, sorted);
  if (subset?.not_found?.length) missing.push(...subset.not_found.map((n) => `${prefix}:${n}`));
  delete subset.not_found;
  chunks.push(JSON.stringify(subset));
}

if (missing.length) {
  console.error(`Icons not found in their collections: ${missing.join(", ")}`);
  process.exit(1);
}

const banner = `// AUTO-GENERATED by scripts/generate-icons.mjs — do not edit by hand.
// Bundles the icon data for every Iconify icon used in src/ so icons render
// offline with no runtime API fetch (and no first-paint icon flash).
"use client";

import { addCollection } from "@iconify/react";

`;

writeFileSync(
  outFile,
  banner + chunks.map((c) => `addCollection(${c});`).join("\n\n") + "\n",
);
const total = [...used.values()].reduce((n, s) => n + s.size, 0);
console.log(`icons.ts written: ${total} icons across ${used.size} collections`);
